spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # create를 자동으로 해줌, application 실행 시점에 지우고 다시 생성
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug # sql이 모두 보이게 설정, logger을 통해서 출력
    org.hibernate.type: trace # 로그에 파라미터를 찍어준다.